Update Python social core
City-of-Helsinki/tunnistamo pull request #114
Opened 2020-04-21 07:44 UTC by vikoivun

social_core 3.3.0 began to update existing user attributes from incoming logins. Attributes used by Django ('username', 'id', 'pk', 'email', 'password', 'is_active', 'is_staff', 'is_superuser') are blacklisted by default. However 'ad_groups' was not. This broke the pipeline, as AD groups are a M2M relation. Workaround was just blacklisting `ad_groups` attribute as well.

2020-11-05 06:59 UTC, tituomin commented
Looks good, rebasing to master and will test.

2020-12-28 15:15 UTC, charn commented
As a side note, for local development environment setup `social-auth-core` version 3.3.3 is required for getting the GitHub OAuth working since with 3.0.0 `AuthCanceled` is raised.

2021-01-08 11:42 UTC, tituomin requested changes
This doesn't seem to try to verify that the 2nd order requirements are in order wrt. the new social auth version.

2021-01-11 07:39 UTC, tituomin commented
> This doesn't seem to try to verify that the 2nd order requirements are in order wrt. the new social auth version.

My bad, there aren't any changes there.

2021-01-11 07:48 UTC, tituomin approved these changes

2021-01-11 07:55 UTC, merged