Add idp_hint parameter support
City-of-Helsinki/tunnistamo pull request #272
Opened 2023-02-23 11:30 UTC by mikkokeskinen

The parameter can be used to filter possible login methods in the login view when logging in via the OIDC provider.

Refs HP-1732

2023-02-27 10:29 UTC, akikoskinen requested changes
Looking nice. Just a few small comments.

2023-02-27 10:29 UTC, akikoskinen commented on tunnistamo/tests/test_auth_error_redirect.py
> +    response_query_parameters = QueryDict(response_url_parts[4])
This part could be a bit more readable without the magic index 4. Perhaps something like:
```suggestion
    response_url_parts = urlparse(response.url)
    response_query_parameters = QueryDict(response_url_parts.query)
```

2023-02-28 06:40 UTC, mikkokeskinen commented
Good points. Made the changes.

2023-02-28 06:44 UTC, akikoskinen approved these changes

2023-02-28 07:32 UTC, merged